platform :ios, '5.1'
inhibit_all_warnings!
pod 'FlurrySDK', '~> 4.2.3'
pod 'RestKit', '~> 0.21.0'
pod 'Reachability', '~> 3.1.1'
pod 'TestFlightSDK', '~> 2.0'
pod 'GoogleConversionTracking', '~> 1.2.0'
pod 'Facebook-iOS-SDK', '~> 3.7.0'
pod 'NSData+Base64', '~> 1.0.0'
target :VstratorCoreTests, :exclusive => true do
    pod 'Expecta', '~> 0.2.2'
    pod 'OCMock', '~> 2.2.1'
    pod 'RestKit/Testing', '~> 0.21.0'
    pod 'MagicalRecord', '~> 2.2'
end